version: '3.9'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=foodbasket
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  api:
    container_name: orders-process
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis
      - remote_server
  redis:
    image: redis:latest
    expose:
      - '6379'
    ports:
      - "6379:6379"
  subcriber:
    build: remote_server
    command: >
      sh -c "python subscriber.py"
    depends_on:
      - redis
    links:
      - redis